
services:
  db:
    build:
      context: ./db
    volumes:
      - db-data:/data

  backend:
    build:
      context: ./backend
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - db-data:/app/data
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    env_file:
      - .env              # pass through BACKEND_URL (see .env-example below)
    ports:
      - "3000:8501"       # map host:container (Streamlit listens on 8501)
    depends_on:
      - backend

volumes:
  db-data:
